call code --install-extension akamud.vscode-theme-onedark
call code --install-extension anseki.vscode-color
call code --install-extension davidbabel.vscode-simpler-icons
call code --install-extension donjayamanne.githistory
call code --install-extension EditorConfig.EditorConfig
call code --install-extension hnw.vscode-auto-open-markdown-preview
call code --install-extension HookyQR.beautify
call code --install-extension k--kato.intellij-idea-keybindings
call code --install-extension krizzdewizz.refactorix
call code --install-extension mohsen1.prettify-json
call code --install-extension ms-vscode.csharp
call code --install-extension msjsdiag.debugger-for-chrome
call code --install-extension robertohuertasm.vscode-icons
call code --install-extension eamodio.gitlens
call code --install-extension heaths.vscode-guid
call code --install-extension ms-dotnettools.csharp
call code --install-extension ms-vscode.powershell
call code --install-extension ms-vsliveshare.vsliveshare-pack
